# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 196)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.soupButton = QtWidgets.QPushButton(self.centralwidget)
        self.soupButton.setGeometry(QtCore.QRect(30, 120, 411, 71))
        self.soupButton.setObjectName("soupButton")
        self.apkFolderPathInputBox = QtWidgets.QLineEdit(self.centralwidget)
        self.apkFolderPathInputBox.setGeometry(QtCore.QRect(130, 80, 251, 21))
        self.apkFolderPathInputBox.setObjectName("apkFolderPathInputBox")
        self.browseFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.browseFileLabel.setGeometry(QtCore.QRect(10, 80, 141, 21))
        self.browseFileLabel.setObjectName("browseFileLabel")
        self.apkSoupLabel = QtWidgets.QLabel(self.centralwidget)
        self.apkSoupLabel.setGeometry(QtCore.QRect(130, 10, 201, 51))
        self.apkSoupLabel.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.apkSoupLabel.setFont(font)
        self.apkSoupLabel.setObjectName("apkSoupLabel")
        self.browseFilesBtn = QtWidgets.QPushButton(self.centralwidget)
        self.browseFilesBtn.setGeometry(QtCore.QRect(390, 80, 75, 23))
        self.browseFilesBtn.setObjectName("browseFilesBtn")
        self.SoupProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.SoupProgressBar.setGeometry(QtCore.QRect(80, 140, 311, 31))
        self.SoupProgressBar.setProperty("value", 24)
        self.SoupProgressBar.setObjectName("SoupProgressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APKSoup 0.0.1"))
        self.soupButton.setText(_translate("MainWindow", "Cook (because soup)"))
        self.browseFileLabel.setText(_translate("MainWindow", "Path to APK's Smali Folder:"))
        self.apkSoupLabel.setText(_translate("MainWindow", "APKSoup Alpha (0.0.1)"))
        self.browseFilesBtn.setText(_translate("MainWindow", "Browse.."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
